---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - goalert.openshift.io.managed.openshift.io
  resources:
  - goalertintegrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - goalert.openshift.io.managed.openshift.io
  resources:
  - goalertintegrations/finalizers
  verbs:
  - update
- apiGroups:
  - goalert.openshift.io.managed.openshift.io
  resources:
  - goalertintegrations/status
  verbs:
  - get
  - patch
  - update
