//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoalertIntegration) DeepCopyInto(out *GoalertIntegration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoalertIntegration.
func (in *GoalertIntegration) DeepCopy() *GoalertIntegration {
	if in == nil {
		return nil
	}
	out := new(GoalertIntegration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GoalertIntegration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoalertIntegrationList) DeepCopyInto(out *GoalertIntegrationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GoalertIntegration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoalertIntegrationList.
func (in *GoalertIntegrationList) DeepCopy() *GoalertIntegrationList {
	if in == nil {
		return nil
	}
	out := new(GoalertIntegrationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GoalertIntegrationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoalertIntegrationSpec) DeepCopyInto(out *GoalertIntegrationSpec) {
	*out = *in
	in.ClusterDeploymentSelector.DeepCopyInto(&out.ClusterDeploymentSelector)
	out.TargetSecretRef = in.TargetSecretRef
	out.GoalertCredsSecretRef = in.GoalertCredsSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoalertIntegrationSpec.
func (in *GoalertIntegrationSpec) DeepCopy() *GoalertIntegrationSpec {
	if in == nil {
		return nil
	}
	out := new(GoalertIntegrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoalertIntegrationStatus) DeepCopyInto(out *GoalertIntegrationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoalertIntegrationStatus.
func (in *GoalertIntegrationStatus) DeepCopy() *GoalertIntegrationStatus {
	if in == nil {
		return nil
	}
	out := new(GoalertIntegrationStatus)
	in.DeepCopyInto(out)
	return out
}
