apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift/configure-goalert-operator?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: 'false'
    pipelinesascode.tekton.dev/max-keep-runs: '3'
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "main"
    pipelinesascode.tekton.dev/pipeline: https://github.com/RedHatInsights/konflux-pipelines/raw/main/pipelines/docker-build-oci-ta.yaml
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: configure-goalert-operator
    appstudio.openshift.io/component: configure-goalert-operator
    pipelines.appstudio.openshift.io/type: build
  name: configure-goalert-operator-on-push
  namespace: fedramp-srep-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/fedramp-srep-tenant/configure-goalert-operator:{{revision}}
  - name: dockerfile
    value: build/Dockerfile
  - name: path-context
    value: .
  taskRunTemplate:
    serviceAccountName: build-pipeline-configure-goalert-operator
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
  pipelineRef:
    resolver: git
    params:
    - name: url
      value: https://github.com/openshift/boilerplate
    - name: revision
      value: master
    - name: pathInRepo
      value: pipelines/docker-build-oci-ta/pipeline.yaml
status: {}
